# Generated by Django 5.2.8 on 2025-11-25 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bot_personality',
            field=models.CharField(default='Friendly', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chats_initiated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_bots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='response_speed',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_chat_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
