# Generated by Django 5.2.8 on 2025-12-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatsession_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dark_mode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='response_speed',
        ),
    ]
