# Generated by Django 5.2.8 on 2025-12-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_userprofile_dark_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botconfiguration',
            name='training_data',
        ),
    ]
