# Generated by Django 5.2.8 on 2025-12-07 15:41

import chat.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_sensitivedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=chat.fields.EncryptedTextField(),
        ),
    ]
