# Generated by Django 5.2.8 on 2025-12-07 15:43

import chat.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chatmessage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=chat.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bot_personality',
            field=chat.fields.EncryptedTextField(default='Friendly'),
        ),
    ]
