# Generated by Django 5.2.8 on 2025-12-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_faq_answer_alter_userprofile_bot_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='keywords',
            field=models.TextField(blank=True, help_text="Comma-separated keywords for semantic matching (e.g., 'account,login,access')"),
        ),
    ]
